// <auto-generated />
using System;
using DataGrid.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataGrid.Persistence.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20240911085757_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataGrid.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArName = "الفئة 1",
                            Name = "Category 1"
                        },
                        new
                        {
                            Id = 2,
                            ArName = "الفئة 2",
                            Name = "Category 2"
                        },
                        new
                        {
                            Id = 3,
                            ArName = "الفئة 3",
                            Name = "Category 3"
                        });
                });

            modelBuilder.Entity("DataGrid.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AddedData")
                        .HasColumnType("date");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("AddedTime")
                        .HasColumnType("time");

                    b.Property<string>("ArDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedData = new DateOnly(2023, 9, 1),
                            AddedOn = new DateTime(2023, 9, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            AddedTime = new TimeOnly(10, 30, 0),
                            ArDescription = "وصف 1",
                            ArName = "منتج 1",
                            CategoryId = 1,
                            Description = "Description 1",
                            Name = "Product 1",
                            Price = 100m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            AddedData = new DateOnly(2023, 9, 2),
                            AddedOn = new DateTime(2023, 9, 2, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            AddedTime = new TimeOnly(11, 45, 0),
                            ArDescription = "وصف 2",
                            ArName = "منتج 2",
                            CategoryId = 2,
                            Description = "Description 2",
                            Name = "Product 2",
                            Price = 200m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            AddedData = new DateOnly(2023, 9, 3),
                            AddedOn = new DateTime(2023, 9, 3, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            AddedTime = new TimeOnly(12, 15, 0),
                            ArDescription = "وصف 3",
                            ArName = "منتج 3",
                            CategoryId = 3,
                            Description = "Description 3",
                            Name = "Product 3",
                            Price = 300m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 4,
                            AddedData = new DateOnly(2023, 9, 4),
                            AddedOn = new DateTime(2023, 9, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedTime = new TimeOnly(13, 0, 0),
                            ArDescription = "وصف 4",
                            ArName = "منتج 4",
                            CategoryId = 1,
                            Description = "Description 4",
                            Name = "Product 4",
                            Price = 400m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 5,
                            AddedData = new DateOnly(2023, 9, 5),
                            AddedOn = new DateTime(2023, 9, 5, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            AddedTime = new TimeOnly(9, 30, 0),
                            ArDescription = "وصف 5",
                            ArName = "منتج 5",
                            CategoryId = 2,
                            Description = "Description 5",
                            Name = "Product 5",
                            Price = 500m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 6,
                            AddedData = new DateOnly(2023, 9, 6),
                            AddedOn = new DateTime(2023, 9, 6, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            AddedTime = new TimeOnly(14, 15, 0),
                            ArDescription = "وصف 6",
                            ArName = "منتج 6",
                            CategoryId = 3,
                            Description = "Description 6",
                            Name = "Product 6",
                            Price = 600m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 7,
                            AddedData = new DateOnly(2023, 9, 7),
                            AddedOn = new DateTime(2023, 9, 7, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            AddedTime = new TimeOnly(10, 45, 0),
                            ArDescription = "وصف 7",
                            ArName = "منتج 7",
                            CategoryId = 1,
                            Description = "Description 7",
                            Name = "Product 7",
                            Price = 700m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 8,
                            AddedData = new DateOnly(2023, 9, 8),
                            AddedOn = new DateTime(2023, 9, 8, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            AddedTime = new TimeOnly(16, 30, 0),
                            ArDescription = "وصف 8",
                            ArName = "منتج 8",
                            CategoryId = 2,
                            Description = "Description 8",
                            Name = "Product 8",
                            Price = 800m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 9,
                            AddedData = new DateOnly(2023, 9, 9),
                            AddedOn = new DateTime(2023, 9, 9, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedTime = new TimeOnly(15, 0, 0),
                            ArDescription = "وصف 9",
                            ArName = "منتج 9",
                            CategoryId = 3,
                            Description = "Description 9",
                            Name = "Product 9",
                            Price = 900m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 10,
                            AddedData = new DateOnly(2023, 9, 10),
                            AddedOn = new DateTime(2023, 9, 10, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            AddedTime = new TimeOnly(11, 30, 0),
                            ArDescription = "وصف 10",
                            ArName = "منتج 10",
                            CategoryId = 1,
                            Description = "Description 10",
                            Name = "Product 10",
                            Price = 1000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 11,
                            AddedData = new DateOnly(2023, 9, 11),
                            AddedOn = new DateTime(2023, 9, 11, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            AddedTime = new TimeOnly(13, 15, 0),
                            ArDescription = "وصف 11",
                            ArName = "منتج 11",
                            CategoryId = 2,
                            Description = "Description 11",
                            Name = "Product 11",
                            Price = 1100m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 12,
                            AddedData = new DateOnly(2023, 9, 12),
                            AddedOn = new DateTime(2023, 9, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedTime = new TimeOnly(12, 0, 0),
                            ArDescription = "وصف 12",
                            ArName = "منتج 12",
                            CategoryId = 3,
                            Description = "Description 12",
                            Name = "Product 12",
                            Price = 1200m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 13,
                            AddedData = new DateOnly(2023, 9, 13),
                            AddedOn = new DateTime(2023, 9, 13, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            AddedTime = new TimeOnly(14, 45, 0),
                            ArDescription = "وصف 13",
                            ArName = "منتج 13",
                            CategoryId = 1,
                            Description = "Description 13",
                            Name = "Product 13",
                            Price = 1300m,
                            Stock = 15
                        });
                });

            modelBuilder.Entity("DataGrid.Domain.Product", b =>
                {
                    b.HasOne("DataGrid.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataGrid.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
